const DATA = [
  //1.1 Los Cambios en la Familia
  {
    "los padres": "parents",
    "los progenitores": "ancestors",
    "los ni\u00f1os": "children",
    "criar una familia": "to bring up a family",
    "los lazos familiares": "family ties",
    convivir: "to live together",
    "la pareja": "couple",
    "el hogar": "home",
    "la familia extensa": "extensive family",
    "la familia extendida": "extended family",
    "los abuelos": "grandparents",
    "los parientes": "relatives",
    "los familiares": "family members",
    "el nieto": "grandchild",
    "el parentesco": "relationship",
    "el primo": "cousin",
    "el sobrino": "nephew",
    "la sobrina": "niece",
    "el t\u00edo": "uncle",
    "la t\u00eda": "aunt",
    "la familia pol\u00edtica": "family-in-law",
    "el cu\u00f1ado": "brother-in-law",
    "la nuera": "daughter-in-law",
    "el suergo": "father-in-law",
    "el yerno": "son-in-law",
    "el padastro": "stepfather",
    "la madastra": "stepmother",
    "la madrina": "godmother",
    "el padrino": "godfather",
    "el ahijado": "godson",
    "el hermanastro": "stepbrother",
    "el hermano de leche": "half brother",
    "la familia acogida": "foster family",
    "la familia de raza mixta": "mixed-race family",
    "la familia disfuncional": "dysfunctional family",
    "la familia ensamblada": "stepfamily",
    "la familia homoparental": "same-sex family",
    "la familia monoparental": "single-parent family",
    "la familia nuclear": "nuclear family",
    "la familia tradicional": "traditional family",
    "una familia poco convencional": "an unconventional family",
    "una familia unida": "a close family",
    "la instituci\u00f3n familiar": "institution of the family",
    "el tutor": "guardian",
    "el padre soltero": "single father",
    "la madre soltera": "single mother",
    "el cabeza de la familia": "head of the family",
    "el hijo en adopci\u00f3n": "child for adoption",
    heterosexual: "heterosexual",
    homosexual: "homosexual",
    "la orientaci\u00f3n sexual": "sexual orientation",
    "ser gay/lesbiana": "to be gay/lesbian",
    "quedarse soltero": "to stay single",
    "la pareja cohabitante": "unmarried couple",
    "la pareja de hecho": "common-law couple",
    "la uni\u00f3n de hecho": "common-law relationship",
    "la convivencia": "living together",
    "la emancipaci\u00f3n": "emancipation",
    "la libertad sexual": "sexual freedom",
    "la maternidad": "maternity",
    "la paternidad": "parenthood",
    "tolerar a los dem\u00e1s": "to tolerate others",
    "la pol\u00e9mica": "controversy",
    controvertido: "controversial",
    "la familia actual": "present-day family",
    "los cambios sociales acelerados": "rapid social changes",
    "los cambios legislativos": "changes in law",
    "la creciente diversidad de las estructuras familiares":
      "the growing diversity of family structures",
    "los cambios radicales": "radical changes",
    "cada vez menos": "less and less",
    "v\u00ednculo matrimonial": "marriage ties",
    "la uni\u00f3n consensual": "(unmarried) consensual union",
    "la proliferaci\u00f3n": "proliferation",
    "el descenso": "decrease",
    "el \u00edndice de natalidad": "birth rate",
    "la natalidad": "birth",
    "tener a los hijos m\u00e1s tarde": "to have children later",
    "el retraso en la edad de matrimonio": "later age of marriage",
    "los nacimientos fuera del matrimonio": "births out of wedlock",
    bisexual: "bisexual",
    transgénero: "trans",
    "las parejas del mismo sexo": "same sex couples",
    "el divorcio": "divorce",
    frecuente: "frequent",
    "el declive de la familia tradicional": "decline of the traditional family",
    "la liberalizaci\u00f3n": "liberalisation",
    "los derechos igualitarios": "equal rights",
    "la planificaci\u00f3n familiar": "family planning",
    "la contracepci\u00f3n": "contraception",
    "la anticoncepci\u00f3n": "contraception",
    "la p\u00edldora anticonceptiva": "contraceptive pill",
    "los m\u00e9todos anticonceptivos": "contraceptive methods",
    "el anticonceptivo": "contraceptive",
    "el preservativo": "condom",
    "el cond\u00f3n": "condom",
    "el aborto": "abortion",
    abortar: "to have an abortion",
    "la fecundaci\u00f3n in vitro": "in vitro (test tube) fertilisation",
    "el ni\u00f1o probeta": "test-tube baby",
    "la inseminaci\u00f3n artificial": "artificial insemination",
    "la madre portadora": "surrogate mother",
    "la fertilidad": "fertility",
    "el embarazo": "pregnancy",
    "un embarazo deseado": "a wanted pregnancy",
    "interrumpir el embarazo": "to terminate the pregnancy",
    envejecer: "to age",
    "estar jubilado": "to be retired",
    "el asilo de ancianos": "old people's home",
    geriátrico: "geriatric",
    "el cuidado de ancianos": "care of the aged",
    "el cuidador": "carer",
    "cumplir el papel de los padres": "to carry out the role of the parents",
    involucrarse: "to get involved",
    "recoger a los ni\u00f1os del colegio":
      "to pick up the children from school",
    criar: "to raise"
  },
  //1.2 Actitudes Hacia el Matrimonio y Divorcio
  {
    "actitudes hacia el matrimonio y el divorcio":
      "attitudes towards marriage and divorce",
    casarse: "to get married",
    "el casamiento": "wedding ceremony",
    "el matrimonio": "marriage",
    "contraer matrimonio": "to get married",
    "la boda": "wedding",
    divorciarse: "to get divorced",
    separarse: "to separate",
    "el esposo": "husband",
    "la esposa": "wife",
    "el prometido": "fiancé",
    prometer: "to promise",
    "prometerse con": "to get engaged to",
    "estar comprometido": "to be engaged",
    "el compromiso matrimonial": "engagement to marry",
    "el noviazgo": "engagement",
    "el contrato de matrimonio": "marriage contract",
    "estar felizmente casados": "to be happily married",
    "el matrimonio infeliz": "unhappy marriage",
    "el fracaso matrimonial": "marital failure",
    "obligados a convivir": "forced to live together",
    "el asesoramiento matrimonial": "marriage guidance",
    "ayudarse uno a otro": "to help each other",
    "el apoyo mutual": "mutual support",
    "el matrimonio homosexual": "gay marriage",
    "mantener un hogar": "to maintain a household",
    "emparentar con una familia": "to marry into a family",
    "el acuerdo prenupcial": "prenuptial agreement",
    "el índice": "rate",
    "el matrimonio civil": "civil marriage",
    "casarse por lo civil": "to have a civil marriage",
    "casarse por la iglesia": "to have a church wedding",
    "casarse de penalti": "to have a shotgun wedding",
    "el novio": "bridegroom",
    "la novia": "bride",
    "la dama de honor": "bridesmaid",
    "el padrino de boda": "best man",
    "llevar un velo": "to wear a veil",
    "el anillo": "ring",
    "los votos matrimoniales": "marriage vows",
    "el salón de bodas": "wedding venue",
    "el banquete de bodas": "wedding banquet",
    "los recién casados": "newly weds",
    "la luna de miel": "honeymoon",
    "las relaciones": "relationships",
    "andar en relaciones con": "to have an affair with",
    "tener relaciones con": "to have an affair with",
    "tener una relación especial con": "to have a special relationship with",
    "estar enamorado de": "to be in love with",
    "llevar una relación sería": "to have a serious relationship",
    "desarrollar una relación": "to develop a relationship",
    "llevar conviviendo x años": "to have been living together for x years",
    "la relación de pareja": "partner relationship",
    "la cohabitación": "cohabitation",
    "el compañero": "partner",
    "el ex cónyuge": "ex-husband",
    "la ex cónyuge": "ex-wife",
    "el amante": "lover",
    "la aventura": "brief affair",
    comportarse: "to behave",
    "la conducta": "behavior",
    entenderse: "to understand each other",
    "la felicidad": "happiness",
    "el respaldo mutuo": "mutual support",
    fiel: "faithful",
    unido: "united",
    estable: "stable",
    "el respeto": "respect",
    "la buena voluntad": "good will",
    "el afecto": "affection",
    cariñoso: "affectionate",
    "la tolerancia": "tolerance",
    "la intolerancia": "intolerance",
    "la fidelidad": "fidelity",
    "la infidelidad": "infidelity",
    "el rompimiento conyugal": "marriage breakdown",
    "el adulterio": "adultery",
    "el rechazo": "rejection",
    "sentir celos": "to feel jealous",
    "los malos tratos": "abuse",
    "la disputa matrimonial": "marital dispute",
    "el cónyuge": "spouse",
    "solicitar un divorcio": "to apply for a divorce",
    "el divorcio contencioso": "contested divorce",
    "la tasa": "rate",
    "el consejero de orientación matrimonial": "marriage guidance counsellor",
    "el consejo": "advice",
    "los trámites de divorcio": "divorce procedures",
    "iniciar los procedimientos del divorcio":
      "to initiate divorce proceedings",
    "el alejamiento": "estrangement",
    "un proceso penoso": "a painful process",
    "la ruptura matrimonial": "marriage break-up",
    "ser incompatibles": "to be incompatible",
    "cuando un matrimonio se deshace": "when a marriage breaks up",
    "la separación": "separation",
    "hijos, bienes y posesiones": "children, property and possessions",
    "el reparto de bienes": "sharing of goods",
    "la pensión alimenticia": "spousal maintenance",
    culpar: "to blame",
    "la culpa": "blame",
    "hablar mal": "to talk badly about",
    "el abogado": "lawyer",
    "el juzgado": "court",
    "la conciliación": "reconciliation",
    "volver a casarse": "to remarry",
    "los derechos de visita": "access rights",
    "tener hijos sin estar casados": "to have children without being married",
    "la baja por maternidad": "maternity leave",
    "la custodia de los niños": "custody of the children",
    "el bienestar de los niños": "well-being of the children",
    "las obligaciones de los padres para con sus hijos":
      "obligations of parents towards their children",
    "la inestabilidad emocional": "emotional instability",
    "la inseguridad": "insecurity"
  },
  //1.3 La Influencia de la Iglesia Católica
  {
    "la religi\u00f3n": "religion",
    religioso: "religious",
    "la oraci\u00f3n": "prayer",
    "el alma": "soul",
    "la fe": "faith",
    influir: "to influence",
    influenciar: "to influence",
    "el cura": "priest",
    "el sacerdote": "priest",
    "el catolicismo": "catholicism",
    "el cielo": "heaven",
    "practicar una religi\u00f3n": "to practice a religion",
    "creer en Dios": "to believe in god",
    "ser creyente": "to be a believer",
    "ser cat\u00f3lico practicante": "to be a practising catholic",
    "el oficio": "service",
    "el culto": "worship",
    orar: "to pray",
    rezar: "to pray",
    "el rezo": "prayer",
    "ir a misa": "to go to mass",
    adorar: "to worship",
    venerar: "to worship",
    bendecir: "to bless",
    "mantener la fe": "to keep the faith",
    "la misericordia": "mercy",
    "las ense\u00f1anzas": "teachings",
    "el mandamiento": "commandment",
    predicar: "to preach",
    "el serm\u00f3n": "sermon",
    convertir: "to convert",
    "la conversi\u00f3n": "conversion",
    "el celibato": "celibacy",
    espiritual: "spiritual",
    divino: "divine",
    devoto: "devout",
    católico: "catholic",
    "el cristianismo": "christianity",
    cristiano: "christian",
    "ser cristiano": "to be a christian",
    "el para\u00edso": "paradise",
    "el evangelio": "gospel",
    "el monje": "monk",
    "el fraile": "friar",
    "la monja": "nun",
    "el ermita\u00f1o": "hermit",
    "la cruz": "cross",
    "los fieles": "the faithful",
    "los feligreses": "congregation",
    sagrado: "sacred",
    santo: "holy",
    "el santo": "saint",
    "la fiesta": "feast day",
    "la parroquia": "parish",
    eclesiástico: "ecclesiastical",
    "el diablo": "devil",
    "el infierno": "hell",
    "el otro mundo": "the other world",
    "los funerales": "funeral",
    "el entierro": "burial",
    enterrar: "to bury",
    pagano: "pagan",
    "la Santa Biblia": "Holy Bible",
    Jesucristo: "Jesus Christ",
    "la Virgen Mar\u00eda": "Virgin Mary",
    "el Padre, el Hijo y el Esp\u00edritu Santo": "Father, Son and Holy Spirit",
    "el milagro": "miracle",
    "la moralidad": "morality",
    "la doctrina": "doctrine",
    "el dogma": "dogma",
    "la teolog\u00eda": "theology",
    "el pecado": "sin",
    pecar: "to sin",
    "el pecador": "sinner",
    "la confesi\u00f3n": "confession",
    perdonar: "to forgive",
    "el arrepentimiento": "repentance",
    "la castidad": "chastity",
    "la Cuaresma": "Lent",
    "el D\u00eda de Reyes": "Twelfth Night",
    "la Pascua de Resurrecci\u00f3n": "Easter",
    "la Semana Santa": "Holy Week",
    "el Pentecost\u00e9s": "whitsun",
    "la procesi\u00f3n": "procession",
    "el romero": "pilgrim",
    "el peregrino": "pilgrim",
    "el santuario": "shrine",
    "la peregrinaci\u00f3n": "pilgrimage",
    "la romer\u00eda": "pilgrimage",
    "el clero": "clergy",
    "el arzobispo": "archbishop",
    "el cardenal": "cardinal",
    "el cl\u00e9rigo": "priest",
    "el obispo": "bishop",
    "el Papa": "Pope",
    "el p\u00e1rroco": "parish priest",
    "el sacerdote obrero": "worker priest",
    "el misionero": "missionary",
    "el designio de Dios sobre la familia": "god's plan for the family",
    "bautizar a un ni\u00f1o": "to baptise a child",
    "el bautizo": "baptism",
    "el control de la natalidad": "birth control",
    "el cuidado de los ni\u00f1os": "care of children",
    "el bienestar de los hijos": "well-being of children",
    "la crianza de los hijos": "upbringing of children",
    "el sacramento de matrimonio": "sacrament of matrimony",
    "el matrimonio indisoluble": "indissoluble nature of marriage",
    "la permanencia del matrimonio": "permanence of marriage",
    "la prohibici\u00f3n del divorcio": "prohibition of divorce",
    "la reconciliaci\u00f3n": "reconciliation",
    "la procreaci\u00f3n": "procreation",
    "anular un matrimonio": "to annul a marriage",
    "la moral sexual": "sexual morality",
    "los deseos sexuales": "sexual desire",
    "las relaciones sexuales prematrimoniales": "premarital sex",
    "el adulterio": "adultery",
    "la tolerancia": "tolerance",
    "la intolerancia": "intolerance",
    "el prejuicio religioso": "religious prejudice",
    "la campa\u00f1a": "campaign",
    "desatar una controversia": "to set off a controversy"
  },
  //2.1 La Influencia de Internet
  {
    "el ordenador": "computer",
    "el port\u00e1til": "laptop",
    "acceder a la red": "to access the web",
    "el correo electr\u00f3nico": "email",
    "el blog": "blog",
    "conectarse con": "to connect up with",
    "en l\u00ednea": "online",
    "la red": "web",
    "el enlace": "link",
    "el archivo": "file",
    "el almacenamiento de datos": "data storage",
    almacenar: "to store",
    apagar: "to turn off",
    archivar: "to file",
    bloquearse: "to crash",
    colapsar: "to crash",
    eliminar: "to delete",
    suprimir: "to delete",
    "la copia de seguridad": "back-up copy",
    "los datos": "data",
    "el esc\u00e1ner": "scanner",
    "la hoja de c\u00e1lculo": "spreadsheet",
    "encender la impresora": "to switch the printer on",
    "la impresora": "printer",
    imprimir: "to print",
    "el listado": "printout",
    "la pantalla": "screen",
    "copiar y pegar": "to copy and paste",
    pulsar: "to press/click",
    "el rat\u00f3n": "mouse",
    "salir del sistema": "to log off",
    "la tecla": "key (on keyboard)",
    "el teclado": "keyboard",
    "la conexi\u00f3n inal\u00e1mbrica": "wireless connection",
    ultrarrápido: "high speed",
    "la wifi": "wifi",
    adjunto: "attached",
    "la arroba": "at symbol (@)",
    "la banda ancha": "broadband",
    buscar: "to search",
    "el buscador": "search engine",
    "la b\u00fasqueda": "search",
    cargar: "to load",
    descargar: "to download",
    "la conexi\u00f3n de alta velocidad": "high speed connection",
    "el correo basura": "junk mail",
    "la direcci\u00f3n": "address",
    engancharse: "to get hooked",
    grabar: "to record",
    guardar: "to save",
    "la herramienta": "tool",
    "mandar por correo electr\u00f3nico": "to send by email",
    "el navegador": "browser",
    "el navegante": "web surfer",
    "el internauta": "internet user",
    navegar: "to surf the web",
    "piratear m\u00fasica": "to illegally download music",
    "el servidor": "server",
    "subir fotos": "to upload photos",
    "la web": "web (website)",
    "la videollamada": "video call",
    abrir: "to open",
    cerrar: "to close",
    "acceder al sistema": "to log on",
    "la base de datos": "database",
    "el banco de datos": "data bank",
    "la conexi\u00f3n de redes": "networking",
    "la clave de acceso": "password",
    "la contrase\u00f1a": "password",
    "el c\u00f3digo": "code",
    "la identificaci\u00f3n por huella dactilar": "fingerprint id",
    "el reconocimiento facial": "facial recognition",
    "la banca electr\u00f3nica": "online banking",
    "hacer clic": "to click",
    "pinchar en": "to click on",
    "el icono": "icon",
    "mover el cursor": "to move the cursor",
    "la p\u00e1gina web": "web page",
    "el men\u00fa": "menu",
    "el sitio web": "website",
    "crear una cuenta": "to create an account",
    "\u00bfhas olvidado la contrase\u00f1a?":
      "have you forgotten your password?",
    "iniciar sesi\u00f3n": "to start a session",
    "las ventas por internet": "internet sales",
    "la tienda online": "online shop",
    "las rese\u00f1as de productos": "product reviews",
    "la cesta de la compra": "shopping basket",
    "la compra en l\u00ednea": "online shopping",
    "las formas de pago aceptadas": "accepted means of payment",
    "los costos de env\u00edo": "delivery costs",
    "evitar largas colas en una tienda": "to avoid long shop queues",
    "la conexi\u00f3n segura": "secure connection",
    "el acceso a la informaci\u00f3n": "access to information:",
    "la sociedad de la informaci\u00f3n": "information society",
    interactivo: "interactive",
    "internet con fines educativos": "internet for educational purposes",
    "la formaci\u00f3n en l\u00ednea": "online learning",
    "la comunidad virtual": "virtual community",
    "el foro online": "online forum",
    "el foro virtual educativo": "virtual educational forum",
    "el intercambio de informaci\u00f3n r\u00e1pido":
      "rapid exchange of information",
    "el soporte en l\u00ednea": "online support",
    "los adelantos tecnol\u00f3gicos": "technological advances",
    "ahorrar tiempo y dinero": "to save time and money",
    "trabajar con m\u00e1s eficacia": "to work more effectively",
    "asimilar las nuevas tecnolog\u00edas": "to assimilate new technologies",
    "la innovaci\u00f3n t\u00e9cnica": "technical innovation",
    "transmitir e intercambiar informaci\u00f3n":
      "to transmit and exchange information",
    "conectarse velozmente": "to link up rapidly",
    "la seguridad": "security",
    "el cortafuegos": "firewall",
    "la ley de protecci\u00f3n de datos": "data protection law",
    "el delito": "crime",
    "el ciberdelito": "cybercrime",
    "el pirata inform\u00e1tico": "hacker",
    "el hacker": "hacker",
    hackear: "to hack",
    fraudulento: "fraudulent",
    "el virus troyano": "trojan virus",
    "el aviso": "warning",
    "el ciberataque": "cyber attack",
    "la alerta sobre virus": "virus alert",
    "el antivirus": "antivirus",
    "eliminar un virus": "to get rid of a virus",
    "la estafa": "scam",
    "los mensajes electr\u00f3nicos no deseados": "unwanted emails",
    "el control parental": "parental control"
  },
  //2.2 Las Redes Sociales: Beneficio y Peligros
  {
    "la aplicaci\u00f3n": "application",
    chatear: "to chat",
    compartir: "to share",
    "la cuenta": "account",
    "el perfil": "profile",
    "la red de amigos": "network of friends",
    "la red social": "social network",
    "el usario": "user",
    enviar: "to send",
    mandar: "to send",
    abonarse: "to subscribe",
    "dar de alta": "to register",
    "la identidad": "identity",
    identificar: "to identify",
    "la privacidad": "privacy",
    "la direcci\u00f3n de correo electr\u00f3nico": "e-mail address",
    "la clave de correo electr\u00f3nico": "e-mail password",
    "la libreta de correo electr\u00f3nico": "e-mail address book",
    "crear un prefil": "to build a profile",
    "la lista de contactos": "contact list",
    "el buscador de amigos": "friend finder",
    solicitar: "to request",
    "la solicitud de amistad": "friend request",
    "hacerse amigos": "to become friends",
    "compartir noticias": "to share news",
    comunicarse: "to communicate",
    "el interlocutor": "conversation partner",
    "el seguidor": "follower",
    "estar al tanto": "to be up to date",
    "entrar en contacto con": "to get in contact with",
    interactuar: "to interact",
    intercambiar: "to exchange",
    interconectar: "to interconnect",
    "el sal\u00f3n de chateo": "chatroom",
    "chatear en l\u00ednea": "to chat online",
    "tener acceso a un chat": "to have access to a chat",
    "enviar mensajes de texto": "to send text messages",
    "dar consejos": "to give advice",
    "postear una foto": "to post a photo",
    "la foto de perfil": "profile picture",
    publicar: "to publish images",
    "la c\u00e1mara digital": "digital camera",
    "etiquetar im\u00e1genes": "to tag pictures",
    "los contenidos": "contents",
    "el emisor de un mensaje": "sender of a message",
    "el receptor de un mensaje": "receiver of a message",
    "el tiempo real": "real time",
    "el historial de b\u00fasquedas": "browsing history",
    "la interfaz": "interface",
    "las citas en l\u00ednea": "online dating",
    "ligar en l\u00ednea": "to flirt online",
    "socializar en l\u00ednea": "to socialise online",
    "la tableta": "tablet",
    tuittear: "to tweet",
    "volverse viral": "to go viral",
    unirse: "to unite",
    vincular: "to link",
    "el bloguero": "blogger",
    "los beneficios": "benefits",
    "relacionarse con los amigos": "to link with friends",
    "recuperar contactos perdidos": "to revive lost contacts",
    "ampliar sus c\u00edrculos de amistades":
      "to widen one's circle of friends",
    "las amistades": "friendships",
    "hacer amigos alrededor del mundo": "to make friends all over the world",
    "facilitar el contacto con los dem\u00e1s":
      "to facilitate contact with others",
    "compartir momentos especiales": "to share special moments",
    recibir: "to receive",
    "realizar foros online": "to hold online forums",
    "utilizar micr\u00f3fonos y c\u00e1maras web":
      "to use microphones and webcams",
    "crear contactos profesionales": "to create professional contacts",
    "la fuente de informaci\u00f3n": "source of information",
    "los temas de actualidad": "topical events",
    "conectar a gente sin importar la distancia":
      "to link up with people irrespective of the distance",
    "eliminar fronteras geogr\u00e1ficas": "to eliminate geographical barriers",
    "enviar mensajes en tiempo real": "to send messages in real time",
    "los peligros": "dangers",
    compulsivo: "compulsive",
    adictivo: "addictive",
    "estar enganchado": "to be hooked on",
    "perder el tiempo": "to waste time",
    perjudicial: "harmful",
    dañino: "harmful",
    "el ciberacoso": "cyberbullying",
    fisgar: "to spy on",
    mentir: "to lie",
    abusar: "to abuse",
    abusador: "abusive",
    chantajear: "to blackmail",
    "el chantaje": "blackmail",
    espiar: "to pry into",
    "ser espiado": "to be spied on",
    "ser v\u00edctima": "to be a victim",
    "la poca fiabilidad de la fuente": "unreliability of the source",
    "los contenidos inapropiados": "inappropriate content",
    "crear una falsa identidad": "to create a false identity",
    "mentir sobre su edad": "to lie about one's age",
    "el fraude": "fraud",
    "los desconocidos": "strangers",
    "interactuar con extra\u00f1os": "to interact with strangers",
    "el virus inform\u00e1tico": "computer virus",
    "quitar privacidad": "to take away privacy",
    "revelar datos personales": "to reveal personal information",
    "robar datos personales": "to steal personal information"
  },
  //2.3 Los Móviles Inteligentes en Nuestra Sociedad
  {
    "el m\u00f3vil inteligente": "smartphone",
    "el mensaje de texto": "text message",
    "la llamada": "call",
    "mandar un mensaje de texto": "to send a text message",
    "ponerse en contacto": "to get in touch",
    telefonear: "to telephone",
    "las novedades tecnol\u00f3gicas": "new technologies",
    "el aparato": "device",
    "el dispositivo": "device",
    "los auriculares": "headphones 12 el buz\u00f3n de voz",
    "el dispositivo manos libres": "hands-free device",
    "el altavoz para m\u00f3vil": "speaker for a mobile",
    "la pantalla t\u00e1ctil": "touch screen",
    "la alerta de bater\u00eda baja": "low battery alert",
    "la bater\u00eda agotada": "dead battery",
    "recargar una bater\u00eda": "to recharge a battery",
    "una pilla": "a battery",
    "el cargador": "charger",
    desenchufar: "to unplug",
    enchufar: "to plug in",
    "el enchufe": "plug",
    "cargar una app": "to load an app",
    "el reproductor de mp3": "mp3 player",
    "capturar una nueva imagen": "to capture a new image",
    "la autofoto": "selfie",
    "la selfie": "selfie",
    "la imagen": "image",
    "las im\u00e1genes": "images",
    "las im\u00e1genes de alta resoluci\u00f3n": "high-resolution images",
    "almacenar datos": "to store information",
    "la mensajer\u00eda instant\u00e1nea": "instant messaging",
    "el tel\u00e9fono inal\u00e1mbrico": "cordless phone",
    "el tel\u00e9fono fijo": "landline",
    "el tono de marcar": "dial tone",
    colgar: "to hang up",
    "la llamada perdida": "missed call",
    funcionar: "to work",
    "el sistema de navegaci\u00f3n por sat\u00e9lite":
      "satellite navigation system",
    "la tarjeta SIM": "SIM card",
    "instalar una aplicaci\u00f3n": "to install an app",
    "el libro electr\u00f3nico": "electronic book",
    "la recepci\u00f3n celular": "mobile reception",
    "el sistema operativo": "operating system",
    "las aplicaciones de pago": "paying apps",
    gratutio: "free",
    "la cobertura celular": "mobile coverage",
    "las aplicaciones de salud": "health apps",
    "comprar juegos": "to buy games",
    "hallar su camino a trav\u00e9s del GPS": "to find your way using GPS",
    "instalar aplicaciones para cualquier uso": "to install apps for any use",
    "leer libros en l\u00ednea": "to read books online",
    "localizar lugares de inter\u00e9s": "to find places of interest",
    "medir la actividad f\u00edsica": "to measure physical activity",
    "mucho espacio de almacenamiento": "lots of storage space",
    "las noticias de \u00faltima hora": "breaking news",
    "organizar una agenda": "to organise a diary",
    "redactar documentos": "to draft documents",
    "reproducir m\u00fasica": "to play music",
    "descargar m\u00fasica": "to download music",
    "revisar el correo": "to check mail",
    "sintonizar la radio": "to tune in to the radio",
    "toda la informaci\u00f3n centrada en un lugar":
      "all the information in one",
    "tomar fotograf\u00edas": "to take pictures",
    "sacar fotograf\u00edas": "to take pictures",
    "hacer videollamadas": "to make videocalls",
    "el inconveniente": "disadvantage",
    "aislar socialmente": "to isolate socially",
    "el aislamiento": "isolation",
    "atraer a ladrones": "to attract thieves",
    "el costo de reemplazo": "the cost of replacement",
    "convertirse en adicto al m\u00f3vil": "to become a mobile addict",
    "la dependencia al usar un m\u00f3vil": "dependency of the mobile",
    "provocar contracturas en el cuello":
      "to cause stiffening of the neck muscles",
    "provocar da\u00f1os oculares": "to damage the eyes",
    "las radiaciones emitidas por los m\u00f3viles":
      "radiation emitted by mobiles",
    "los s\u00edntomas nocivos para la salud f\u00edsica y mental":
      "harmful symptoms for physical and mental health",
    "si no est\u00e1s conectado no eres nadie":
      "if you aren\u2019t online, you\u2019re a nobody"
  },
  //3.1 La Mujer en el Mercado Laboral
  {
    "el mundo laboral": "the world of work",
    "el puesto": "position",
    "la desigualdad": "inequality",
    equitativo: "equitable",
    cobrar: "to earn",
    ganar: "to win",
    "el trabajador": "worker",
    "el obrero": "laborer",
    "la carrera": "career",
    "la compa\u00f1\u00eda": "company",
    "la emprasa": "business",
    "el empleo": "employment",
    "el paro": "unemployment/strike",
    "el desempleo": "unemployment",
    "la actividad laboral": "work",
    "adaptarse a las necesidades del mercado":
      "to adapt to the needs of the  market",
    "la ambici\u00f3n": "ambition",
    "el aprendiz": "apprentice",
    "el aprendizaje": "apprenticeship",
    "la brecha salarial": "wage gap",
    "el comercio": "business",
    "la demanda de trabajo": "demand for",
    "el despido": "dismissal",
    "la desventaja": "disadvantage",
    "la experiencia laboral": "work experience",
    "la formaci\u00f3n profesional": "vocational training",
    "el modelo": "model",
    "la mujer asalariada": "salaried women",
    "la oferta de mano de obra": "labour supply",
    "el oficio": "trade",
    "el per\u00edodo de inactividad": "period of inactivity",
    "la prestaci\u00f3n": "benefit",
    "protestar por los bajos sueldos": "to protest at low salaries",
    "el salario por hora": "hourly rate of pay",
    "el sector (de) servicios": "service sector",
    "la soltera": "single women",
    "la tasa de actividad": "rate of employment",
    "el trabajo de oficina": "office work",
    "solicitar un puesto de trabajo": "to apply for a job",
    "el anuncio": "advertisement",
    "las ofertas de trabajo": "situations vacant",
    "la agencia de colocaci\u00f3n": "employment agency",
    "hacer oposiciones": "to seek a job by public competition",
    "el curr\u00edculum (vitae)": "CV (curriculum vitae)",
    "los datos personales": "personal data",
    "los t\u00edtulos acad\u00e9micos": "academic qualifications",
    "la experiencia profesional": "professional experience",
    "la entrevista": "interview",
    "el rechazo": "rejection",
    "las ambiciones": "ambitions",
    "ser ambicioso": "to be ambitious",
    "buscarse ina carrera en...": "to seek a career in...",
    "apuntar alto": "to aim high",
    "sacar adelante la carrera": "to advance  one's career",
    "aspirar a...": "to have aspirations to be...",
    "estudiar para abogado": "to study to become a lawyer",
    "trabajar de...": "to work as...",
    "el personal": "personnel",
    "el puesto de alta direcci\u00f3n": "senior management position",
    "hacer pr\u00e1cticas": "to work as an intern",
    "el pasante": "intern",
    "la pasant\u00eda": "internship",
    "el director de ventas": "sales manager",
    "el director de personal": "personnel manager",
    "los altos cargos": "senior management",
    "el empresario": "manager",
    "la plantilla": "staff",
    "la mano de obra": "workforce",
    "el funcionario": "civil servant",
    "el empleado": "employee",
    "el trabajador eventual": "casual worker",
    "el jornalero": "day labourer",
    "el trabajo de cuello blanco": "white-collar job",
    "el trabajo de obrero": "blue-collar job",
    "ser trabajador aut\u00f3nomo": "to be self-employed",
    experimentado: "experienced",
    "cambiar de empleo": "to change jobs",
    "la satisfacci\u00f3n en el trabajo": "job satisfaction",
    "el estatus": "status",
    "el mercado de trabajo": "labour market",
    "el contrato": "contract",
    "el sector de servicios": "service sector",
    contratar: "to contract",
    "el trabajo a tiempo completo": "full-time work",
    "el trabajo a tiempo parcial": "part-time work",
    "el trabajo a destajo": "piecework",
    "el trabajo con horario flexible": "flexitime job",
    "la flexibilizaci\u00f3n de horarios": "flexitime",
    "el trabajo por turnos": "shiftwork",
    "trabajar horas extra": "to work overtime",
    "la jornada completa": "full working day",
    "el pluriempleo": "having more than one job",
    "el salario m\u00ednimo": "minimum wage",
    "el sueldo": "salary",
    "las posibilidades de ascenso": "promotional possibilities",
    "sentirse a gusto en el trabajo": "to feel happy in one's work",
    "el empleo temporal": "temporary work",
    "la ama de casa": "housewife",
    "realizar los trabajos de la casa": "to do housework",
    "el trabajo dom\u00e9stico": "housework",
    "el cuidado de la familia": "care of the family",
    "el servicio dom\u00e9stico": "domestic service",
    "la empleada de hogar": "domestic help",
    "la criada": "maid",
    "la ni\u00f1era": "nanny",
    "la limpieza": "cleaning",
    "el limpiador": "cleaner",
    planchar: "to iron",
    coser: "to sew",
    "la costura": "dressmaking",
    "la mano de obra barata": "cheap labor",
    "el trabajo de los campos": "work in the fields",
    "el bajo sueldo": "low salary",
    "el empleo bien pagado": "well-paid job",
    "la falta de cualificaciones": "lack of qualifications",
    "la falta de formaci\u00f3n profesional": "lack of job training",
    "el empleo actual": "current job",
    "incorporarse al mercado laboral": "to enter the job market",
    "la formaci\u00f3n educativa": "educational training",
    "la carrera profesional": "professional career",
    "el mayor acceso a la formaci\u00f3n": "better access to training",
    "el desarrollo profesional": "professional development",
    "la oportunidad": "opportunity",
    "el horario flexible": "flexible hours",
    "las perspectivas laborales": "job prospects",
    "la creciente participaci\u00f3n de las mujeres casadas":
      "the increasing participation of married women",
    "el descenso de la tasa de fecundidad": "decline in the fertility rate",
    "la reducci\u00f3n de la tasa natalidad": "reduction of the birth rate",
    "la necesidad de compaginar la vida familiar con la profesional":
      "need to reconcile family and professional life",
    "compartir las tareas dom\u00e9sticas": "to share the housework",
    "el cuidado del hogar": "household chores",
    "la guarder\u00eda":
      "creche 145, solicitar un permiso para el cuidado de los hijos",
    "el retraso de la edad del matrimonio": "later age of marriage",
    "el incremento del trabajo aut\u00f3nomo": "increase in self-employment",
    "el techo de cristal": "glass ceiling",
    "el impacto en la vida dom\u00e9stica": "impact on family life",
    "buscar el equilibrio entre el trabajo y la vida personal":
      "to seek a work-life balance",
    "la trabajadora con cargas familiares":
      "female worker with family responsabilities",
    "seguir realizando las tareas dom\u00e9sticas":
      "to continue to do housework",
    "tener una doble jornada de trabajo": "to have a double working day",
    "el permiso de maternidad": "maternity leave",
    "la baja por maternidad": "maternity leave",
    "la paga por maternidad": "maternity pay",
    "el costo de cuidado de ni\u00f1os": "cost of childcare after the children",
    "la excendencia por cuidado de los ni\u00f1os": "parental leave",
    "la planificaci\u00f3n familiar": "family planning",
    "estar embarazada": "to be pregnant",
    "la discriminaci\u00f3n salarial": "wage discrimination",
    "la discriminaci\u00f3n por raz\u00f3n de sexo": "sexual discrimination",
    "estar peor pagadas que los hombres": "to be less well paid than men",
    "cobrar el 10 por ciento menos": "to earn 10 per cent less",
    "pocas mujeres ocupan los altos cargos": "few women occupy the top jobs"
  },
  //3.2 El Machismo y el Feminismo
  {
    "la discriminaci\u00f3n de g\u00e9nero": "gender discrimination",
    "el g\u00e9nero": "gender",
    "la demanda de igual remuneraci\u00f3n": "demand for equal pay",
    "el prejuicio": "prejudice",
    "el acoso sexual": "sexual harassment",
    luchar: "to fight",
    "el machista": "male chauvinist",
    "el aborto": "abortion",
    "la autoestima": "self-esteem",
    controvertido: "controversial",
    "las desigualdades entre varones y mujeres":
      "inequality between men and women",
    dominar: "to dominate",
    "los estereotipos sexuales": "sexual stereotypes",
    "la liberaci\u00f3n": "freedom",
    desfavorecido: "disadvantaged",
    descatar: "to stand out",
    discriminatorio: "discriminatory",
    erradicar: "to eradicate",
    "el estereotipo": "stereotype",
    "garantizar la paridad de g\u00e9nero": "to guarantee gender equality",
    "la hembra": "female",
    "la igualdad de oportunidades": "equality of opportunities",
    inferior: "inferior",
    lograr: "to achieve",
    privar: "to deprive",
    reivindicar: "to claim (demand)",
    reclamar: "to demand (claim)",
    rechazar: "to reject",
    "el respeto": "respect",
    "el sexo femenino": "(the) female sex",
    "el sexo masculino": "the (male) sex",
    "tratar en igualdad a las mujeres": "to treat women equally",
    "la v\u00edctima": "victim",
    "el activista": "activist",
    "conseguir la igualdad": "to achieve equality",
    "la dependencia": "dependency",
    "el derecho a votar en igualdad con los varones":
      "the right to vote the same as men",
    "la emancipaci\u00f3n feminista": "emancipation of women",
    "eliminar barreras": "to break down barriers",
    "exigir derechos": "to demand rights",
    "la explotaci\u00f3n": "exploitation",
    indignado: "outraged",
    "el luchador": "fighter",
    "la lucha por los derechos de la mujer": "the fight for women's rights",
    "la lucha por la igualdad": "(the) fight for equality",
    "la manifestaci\u00f3n": "demonstration",
    "la pionera": "pioneer",
    prohibir: "to prohibit",
    "el reconocimiento": "recognition",
    "la subordinaci\u00f3n patriarcal":
      "subordination to a patriarchal society",
    "el sufragismo": "women's suffrage movement",
    "el sufragio universal": "universal suffrage",
    "la sufragista": "suffragette",
    sumiso: "submissive",
    "el voto": "vote",
    aguantar: "to put up with",
    "el derecho de trabajar": "(the) right to work",
    "la discriminaci\u00f3n positiva": "positive discrimination",
    empoderarse: "to empower",
    "el eslogan": "slogan",
    "el \u00e9xito": "success",
    "igual salario por igual trabajo": "equal pay for equal work",
    "la igualdad con los hombres en su nivel de ingresos":
      "equality with men in their income level",
    "la legislaci\u00f3n a favor de la mujer": "legislation in favour of women",
    "la Ley de Igualdad de 2007": "Equal Opportunities Act 2007",
    "el jucio": "judgement (trial)",
    "los derechos humanos": "human rights",
    mejorar: "improve",
    "reivindicar derechos como trabajadoras":
      "to demand rights as female workers",
    "romper estereotipos": "to break stereotypes",
    "el movimiento feminista": "feminist movement",
    "la toma de conciencia": "raising of awareness",
    acosar: "to harass (bully)",
    agresivo: "aggressive"
  },
  //3.3 Los Derechos de los gays y las personas trans
  {
    "el gay": "gay",
    "la lesbiana": "lesbian",
    "el homosexual": "homosexual",
    transgénero: "transgender",
    "la orientaci\u00f3n sexual": "sexual orientation",
    "la identidad de g\u00e9nero": "gender identity",
    "la igualdad de derechos": "equal rights",
    andrógino: "androgynous",
    "la bisexualidad": "bisexuality",
    "la homosexualidad": "homosexuality",
    "salir del armario": "to come out of the closet",
    LGTBQ: "LGBTQ",
    "cambiar la identidad": "to change identity",
    "la reasignaci\u00f3n de sexo": "gender reassignment",
    "el tratamiento hormonal": "hormonal treatment",
    "la intimidad": "intimacy",
    "las relaciones sexuales": "sexual relations",
    "llevar a cabo": "to carry out",
    "el amante": "lover",
    amoroso: "loving",
    "el apoyo": "support",
    "la aventura": "brief affair",
    coquetar: "to flirt",
    ligar: "to hook up (flirt)",
    "el devaneo": "flirtation",
    "el ligue": "affair",
    "la adopci\u00f3n gay": "gay adoption",
    "el matrimonio gay": "gay marriage",
    "la uni\u00f3n civil": "civil partnership",
    "la pareja del mismo sexo": "same-sex couple",
    "el desfile": "parade",
    "el orgullo gay": "gay pride",
    orgulloso: "proud",
    "el colectivo homosexual": "gay community",
    "la asociaci\u00f3n LGTB": "LGBT association",
    "el establecimiento gay": "gay bar",
    "el grupo gay": "gay group",
    "la bandera del arco iris": "rainbow flag",
    "la minoria": "minority",
    "las percepciones de la sociedad": "society's perceptions",
    progresista: "progressive",
    "los avances sociales destacados": "significant social progress",
    acogedor: "welcoming",
    "la tolerancia": "tolerance",
    "el reconocimiento": "recognition",
    "la integraci\u00f3n": "integration",
    "tratar por igual a todo el mundo": "to treat everyone equally",
    amanerado: "mannered",
    aberrante: "aberrant",
    "la naturaleza": "nature",
    "el rechazo": "rejection",
    "el acoso escolar": "school bullying",
    "la ignorancia": "ignorance",
    "el estereotipo": "stereotype",
    "la homofobia": "homophobia",
    "ser homof\u00f3bico": "to be homophobic",
    marginado: "marginalised",
    "sufrir discriminaci\u00f3n": "to suffer discrimination",
    "el VIH (virus de la inmunodeficiencia humana)":
      "HIV (human immunodeficiency virus)",
    "el SIDA": "AIDS",
    "restringir la libertad individual":
      "to restrict the freedoms of individuals",
    "el trato desigual": "unequal treatment",
    "abogar por los derechos humanos": "to champion human rights",
    "luchar por el reconocimiento de sus derechos":
      "to fight for recognition of one's rights",
    "defender los derechos LGTB": "to defend LGBT rights",
    "el reconocimiento legal del matrimonio gay":
      "legal recognition of gay marriage",
    "proteger los derechos b\u00e1sicos": "to protect basic human rights",
    legalizar: "to legalise",
    "la legislaci\u00f3n contra delitos de odio":
      "legislation against hate crimes",
    "las violaciones de derechos humanos": "breaches of human rights",
    "denunciar las agresiones contra los LGTBQ":
      "to report aggression against LGTBQ people"
  },
  //4.1 Cantantes y Músicos
  {
    "el m\u00fasico": "musician",
    "el cantante": "singer",
    cantar: "to sing",
    "la canci\u00f3n": "song",
    "la letra": "lyrics",
    "el concierto": "concert",
    "la estrella de pop": "pop star",
    "la m\u00fasica pop": "pop music",
    tocar: "to play",
    "la influencia": "influence",
    "el modelo a seguir": "role model (to follow)",
    "el modelo a imitar": "role model (to imitate)",
    "el \u00e1lbum": "album",
    "el artista predilecto": "favourite artist",
    "los auriculares": "headphones",
    "la carrera": "career",
    "dedicarse a": "to devote oneself to",
    "descargar m\u00fasica": "to download music",
    "la entrevista": "interview",
    "el \u00e9xito": "success",
    exitoso: "successful",
    "la fama": "fame",
    fomentar: "to promote",
    "el \u00eddolo de pop": "pop idol",
    increíble: "incredible",
    "las listas de \u00e9xitos": "charts",
    "llegar a la cima": "to reach the top",
    "la melod\u00eda": "melody",
    "el pinchadiscos": "dj",
    "promocionar una canci\u00f3n": "to promote a song",
    rítmico: "rhythmic",
    tararear: "to hum",
    "el tocadiscos": "record player",
    "el rapero": "rapper",
    "el rockero": "rock singer",
    "el solista": "soloist",
    "la artista": "artist",
    "la banda de reggae": "reggae band",
    "el conjunto pop": "pop group",
    "la melena": "long hair",
    "la m\u00fasica indie": "indie music",
    "la m\u00fasica rock": "rock music",
    "la m\u00fasica metal": "metal music",
    "la m\u00fasica punk": "punk music",
    "la m\u00fasica folk": "folk music",
    "la m\u00fasica de c\u00e1mara": "chamber music",
    "la m\u00fasica antigua": "early music",
    "la m\u00fasica cl\u00e1sica": "classical music",
    "la m\u00fasica \u00e9tnica": "ethnic music",
    "la m\u00fasica sacra": "sacred music",
    "la actuaci\u00f3n": "performance",
    "el festival pop": "pop festival",
    actuar: "to act",
    interpretar: "to play (perform)",
    "el acompa\u00f1amiento musical": "musical accompaniment",
    "el escanario": "stage",
    "la escena": "scene",
    "el espect\u00e1culo": "performance",
    "la audiencia": "audience ",
    "el p\u00fablico": "audience ",
    "los fans": "fans",
    "el espectador": "spectator",
    "en directo": "live ",
    "en vivo": "live ",
    "ir a ver una banda en vivo": "to go to see a live band",
    apluadir: "to applaud",
    emitir: "to broadcast",
    "el altavoz": "speaker",
    amplificar: "to amplify",
    "el micr\u00f3fono": "microphone",
    "los focos": "lights",
    "el sistema de amplificaci\u00f3n": "PA system",
    "los amplificadores": "loudspeakers (amplifiers)",
    "las luces estrobosc\u00f3picas": "strobe lights",
    "el sintetizador": "synthesiser",
    "el teclado": "keyboard",
    "tocar la bater\u00eda": "to play the drums",
    "tocar la guitarra el\u00e9ctrica": "to play (the) electric guitar",
    "el telonero": "support act",
    "la grabaci\u00f3n": "recording",
    "el disco n\u00famero uno": "number one hit",
    "la copia digital": "digital copy",
    "transmitir los archivos de m\u00fasica": "to stream music files",
    "descargar un \u00e1lbum": "to download an album",
    "reproducir m\u00fasica de forma inal\u00e1mbrica":
      "to stream music wirelessly",
    "el sencillo": "single",
    "el disco compacto": "CD",
    "la pista": "track",
    "lanzar un sencillo": "to launch a single",
    "el lanzamiento de un sencillo": "launch of a single",
    "el sello discogr\u00e1fico": "record label",
    "escuchar m\u00fasica con un reproductor de mp3":
      "to listen to music with an mp3 player",
    "la disponabilidad de m\u00fasica gratuita": "availability of free music",
    "las tiendas de m\u00fasica en l\u00ednea": "online music shops",
    "comprar m\u00fasica a las plataformas en l\u00ednea":
      "to buy music from online platforms",
    "subscribirse a un sitio online de m\u00fasica":
      "to subscribe to an online music website",
    "infringir la ley": "to break the law",
    "la m\u00fasica pirateada": "pirated music",
    "escuchar m\u00fasica sin pagar":
      "to listen to music without paying for it",
    "descargar m\u00fasica ilegalmente": "to listen to music ilegally",
    "la copia legal": "legal copy",
    admirar: "to admire",
    "influir en": "to have an influence on",
    influyente: "influential",
    idealizar: "to idealize",
    chiflar: "to like",
    "identificarse con": "to identify oneself with",
    idolatrar: "to idolize",
    imitar: "to imitate",
    carismático: "charismatic",
    "el magnetismo": "charisma",
    humilde: "humble",
    "la humilidad": "humility",
    contreverido: "controversial",
    "el talento": "talent",
    "una mala influencia sobre los j\u00f3venes":
      "a bad influence on the young",
    "el uso de las drogas": "use of drugs 118 tomar drogas",
    "imitar el comportamiento de un idolo":
      "to imitate the behaviour of an idol",
    "imitar a su artista predilecta": "to imitate one's favourite artist",
    "la mala conducta": "bad behaviour",
    "jugar a ser superestrella de la m\u00fasica":
      "to play at being a music superstar",
    "la banda sonora": "soundtrack",
    "la lacra": "blemish",
    pegadizo: "catchy",
    revolucionar: "to revolutionise",
    "el ritmo bailable": "danceable rhythm",
    "saltar a estrellato": "to become a star",
    "el sonido": "sound",
    versionar: "to make a new version of",
    "la balada": "ballad",
    "la barriga llena": "full stomach",
    "la buena voluntad": "good will",
    "el cantuator": "singer-songwriter"
  },
  //4.2 Estrellas de Televisión y Cine
  {
    "la televis\u00f3n": "television",
    "el televisor": "television set",
    "el canal": "channel",
    "la cadena": "TV network",
    "la pel\u00edcula": "film",
    "el filme": "film",
    "el actor": "(male) actor",
    "la actriz": "",
    "la estrella de cine": "film star",
    "el rol": "role (part)",
    "el papel": "role",
    "la pantalla": "screen",
    adapatar: "to adapt",
    célebre: "famous",
    "la celebridad": "celebrity",
    "la comedia": "comedy",
    conocido: "well-known",
    conseguir: "to achieve ",
    lograr: "to achieve ",
    entretenido: "entertaining",
    entrevistar: "to interview",
    "la estrella medi\u00e1tica": "media star",
    famoso: "famous",
    fascinante: "fascinating",
    "la gala": "gala (show)",
    galardonar: "to reward",
    "el ganador": "winner",
    ganar: "to win",
    "el int\u00e9rprete": "performer",
    "la personalidad": "personality",
    "los personajes m\u00e1s queridos": "most-loved characters",
    popular: "popular",
    predilecto: "favorite",
    preferido: "preferred tener \u00e9xito",
    "tener \u00e9xito": "to be successful",
    "el t\u00edtulo": "title",
    "el triunfo": "victory",
    "poner la tele": "to turn on the TV",
    "quitar la tele": "to turn off the TV",
    "ver televisi\u00f3n en linea": "to watch television online",
    "el receptor": "receiver",
    "salir por la tele": "to appear on TV",
    presentar: "to present (host)",
    "el presentador": "presenter",
    "el televidente": "television viewer",
    "el telespectador": "television viewer",
    "el programa": "programme",
    "la programaci\u00f3n": "programme times",
    "la gama amplia de canales": "wide range of channels",
    "la pantalla chica": "small screen",
    "la caja tonta": "box (television)",
    "el mando a distancia": "remote control",
    "la televisi\u00f3n por cable": "cable television",
    "la televisi\u00f3n por sat\u00e9lite": "satellite television",
    "el telediario": "TV news programme",
    "las noticias": "news",
    "los anuncios": "advertisements",
    "la telerrealidad": "reality TV",
    "la telenovela": "soap opera (tele..)",
    "el culebr\u00f3n": "soap opera ",
    "el dibujo animado": "cartoon",
    "el concurso": "competition ",
    "el certamen": "competition ",
    "el concursante": "competitor stars",
    "las estrellas de la telerrealidad": "reality show",
    "la serie": "series",
    "la violencia televisiva": "television violence",
    "en directo": "live",
    "el disco de video digital (DVD)": "DVD",
    "el v\u00eddeo": "video",
    "el clip de video": "video clip",
    "grabar en video": "to record on video",
    "la taquilla": "box office",
    protagonizar: "to star in",
    "el actor principal": "main actor",
    "el actor de reparto": "supporting actor",
    "el personaje": "character",
    "desempe\u00f1ar un papel": "to play a role",
    "a lo largo de su carrera": "throughout his career",
    "el estreno": "premiere",
    "estrenar una pel\u00edcula": "to put on a film for the first time",
    "poner una pel\u00edcula": "to show a film",
    "gozar del cine": "to enjoy the cinema",
    "la c\u00e1mara": "camera",
    filmar: "to film",
    "el director": "director",
    dirigir: "to direct",
    "el cineasta": "filmmaker",
    "la banda sonora": "soundtrack",
    "el exitazo": "smash hit",
    adorar: "to adore",
    distinguido: "distinguished",
    elegante: "elegant",
    guapo: "handsome",
    "el h\u00e9roe": "hero",
    "la her\u00f3ina": "heroine",
    hechizar: "to bewitch",
    influenciado: "influenced",
    impresionar: "to impress",
    poderoso: "powerful",
    "la superestrella": "superstar"
  },
  //4.3 Modelos
  {
    "el modelo": "model",
    "el \u00eddolo": "idol",
    "el deportista": "sportsman",
    "el seguidor": "follower",
    "el aficionado": "fan",
    "la moda": "fashion",
    "el estilo": "style",
    "la imagen": "image",
    aparecer: "to appear",
    "la campa\u00f1a publicitaria": "advertising campaign",
    "el culto a la celebridad": "cult of celebrity",
    destacar: "to stand out",
    "el fen\u00f3meno": "phenomenon",
    "la foto": "photo",
    "la pasi\u00f3n": "passion",
    "la portada de revista": "magazine cover",
    promocionar: "to promote",
    "la publicidad": "publicity",
    publicitario: "advertising",
    sobresaliente: "outstanding",
    sobresalir: "to stand out",
    "el supermodelo": "supermodel",
    rubio: "blonde",
    moreno: "brunette",
    "la l\u00ednea": "figure",
    anoréxico: "anorexic",
    "el modelaje": "modelling",
    posar: "to pose",
    "el porte": "bearing",
    "la prenda de vestir": "garment",
    "la manera de vestirse": "way of dressing",
    "tener un buen aspecto": "to look good",
    "expresar su personalidad en la ropa":
      "to express one's personality in one's clothes",
    "el dise\u00f1ador": "designer",
    "la marca": "brand",
    "la ropa de dise\u00f1o": "designer clothes",
    "la marca de moda": "designer label",
    "el modisto": "fashion designer",
    "estar muy de moda": "to be very trendy",
    "a la \u00faltima moda": "the latest fashion",
    "pasar de moda": "to go out of fashion",
    "el atuendo": "dress",
    "lucir un nuevo vestido": "to show off a new dress",
    "la preocupaci\u00f3n por vestir bien": "the desire to be well-dressed",
    "saber c\u00f3mo vestir": "to know how to dress",
    vistoso: "flashy",
    "los vaqueros rotos": "ripped jeans",
    "el peinado": "hairstyle",
    "el maquillaje": "makeup",
    maquillarse: "to put on makeup",
    "la pasarela": "catwalk",
    "el atleta": "athlete",
    "el jugador": "player",
    disputar: "to compete for",
    "batir el r\u00e9cord": "to break the record",
    "superar el reto": "to overcome a challenge",
    vencer: "to conquer",
    "la medella de oro": "gold medal",
    "el medallero": "medal haul",
    "el campe\u00f3n": "champion",
    "el campeonato": "championship",
    "el fan\u00e1tico": "fan",
    "el hincha": "(football) fan",
    amar: "to love",
    "el atractivo fisico": "physical attraction",
    "dar ejemplo": "to set an example",
    "ejercer influencia en": "to exert influence on",
    inspirar: "to inspire",
    seguir: "to follow",
    venerar: "to worship",
    "valorar la riqueza material": "to value material wealth",
    "sobrevalorar la celebridad": "to overrate celebrity",
    "el genio": "genius",
    "el culto al h\u00e9roe": "hero-worship",
    "el icono": "icon",
    dedicado: "dedicated",
    bello: "beautiful",
    "la belleza": "beauty",
    bronceado: "tanned",
    impactante: "striking",
    inalcanzable: "unobtainable",
    "el trastorno alimenticio": "eating disorder",
    "el accesorio": "accessory",
    adelgazar: "to lose weight",
    "la altura": "height",
    anticuado: "old-fashioned",
    "la apariencia": "appearance",
    "atraer la atenci\u00f3n": "to catch the eye",
    "el compatriota": "fellow citizen",
    "dar la enhorabuena": "to congratulate",
    "la delgadez": "thinness",
    desfile: "parade",
    desfilar: "to walk in a parade",
    engordar: "to gain weight",
    esclavizar: "to enslave",
    esquelético: "skeletal"
  },
  //5.1 Tradiciones y Costumbres
  {
    "el carnaval": "carnival",
    "la corrida": "bullfight",
    "la costumbre": "custom",
    "el desfile": "parade. procession",
    "disfrutar de": "to enjoy",
    "el espect\u00e1culo": "performance",
    festejar: "to celebrate",
    "los fuegos artificiales": "fireworks",
    "ir de tapeo": "to go out to eat tapas",
    "el participante": "participant",
    pasear: "to go for a walk",
    "la romer\u00eda": "pilgrimage",
    "el traje": "costume",
    "acostumbrarse a hacer": "to be accustomed to doing",
    "la costumbre t\u00edpica": "typical custom",
    originariamente: "originally",
    "su origen se remonta a": "its origin goes back to",
    "influenciado/a por la cultura \u00e1rabe": "influenced by Arabic culture",
    simbolizar: "to symbolise",
    "el festejo": "party (celebration)",
    "la celebraci\u00f3n": "celebration",
    "la festividad": "festivity",
    "adornado/a con flores": "decorated with flowers",
    "el cartel": "poster",
    "el espect\u00e1culo \u00fanico": "unique spectacle",
    "iluminado por velas": "illuminated by candlelight",
    "el ambiente de la fiesta": "festive atmosphere",
    "la cabalgata": "mounted procession",
    "la carroza": "float",
    "la bodega": "wine cellar",
    "la carrera de caballos": "horse race",
    "la carreta": "cart",
    "la verbena": "open-air party",
    "dar la bienvenida": "to welcome",
    "los conocidos espect\u00e1culos": "well-known spectacles",
    desfilar: "to walk in a parade (or procession)",
    "el recorrido": "tour",
    "salir a recorrer las calles": "to go out and walk through the streets",
    "el casco antiguo": "old town",
    "todo el pueblo participa": "the whole town takes part",
    atraer: "to attract",
    "esta tradici\u00f3n atrae of people a miles de personas":
      "this tradition attracts thousands",
    "la concurrencia": "attendance. spectators",
    "la cuaresma": "Lent",
    "Domingo de Resurrecci\u00f3n": "Easter Sunday",
    "Mi\u00e9rcoles de Ceniza": "Ash Wednesday",
    "Viernes Santo": "Good Friday",
    "(el d\u00eda de) Navidad": "Christmas Day",
    "las Navidades": "Christmas Season",
    "la Nochebuena": "Christmas Eve",
    navideño: "(relating to) christmas",
    "los Reyes Magos": "Three Wise Men",
    "la cofrad\u00eda": "brotherhood",
    "la cruz": "cross",
    devoto: "devout",
    "la ermita": "hermitage",
    "los fieles": "the faithful",
    "el nazareno": "penitent",
    "el patrono": "patron saint",
    "la procesi\u00f3n": "procession",
    "rememorar la pasi\u00f3n de Jesucristo": "to commemorate Christ's passion",
    sagrado: "sacred",
    santo: "holy",
    "venerar a la Virgen": "to worship the Virgin Mary",
    "las fiestas profanas": "secular festivals",
    "las campanadas de A\u00f1o Nuevo": "the chimes at New Year",
    "las doce uvas de Nochevieja": "the twelve grapes on New Year's Eve",
    "la feria": "fair",
    festivo: "festive",
    folklórico: "folkloric",
    "la iluminaci\u00f3n": "lighting",
    "la m\u00e1scara": "mask",
    "el mu\u00f1eco": "effigy (model of a person)",
    "la nochevieja": "new year's eve",
    "el cohete": "rocket",
    "el petardo": "firecracker",
    "la pirotecnia": "pyrotechnics",
    "el Carnaval de las Palmas de Gran Canaria": "Las Palmas carnival",
    "las Fallas": "fallas (bonfire & fireworks festival in Valencia)",
    "la Feria de Abril": "Seville Fair",
    "las Hogueras de San Juan": "Bonfire Night in Alicante",
    "los moros y cristianos": "Moors and Christians festival, Alcoy",
    "San Isidro": "bullfighting festival, Madrid",
    "los Sanfermines": "week of bullfighting in Pamplona",
    "la Tomatina": "tomato throwing festival in Bu\u00f1ol",
    "Semana Santa": "holy week",
    "la virgen del roc\u00edo":
      "procession to the hermitage at El Roc\u00edo to worship the Virgin Mary (Pentecost)",
    lucir: "to sport (to wear)",
    "el vestido": "dress",
    "la vestimenta": "clothing",
    vestirse: "to get dressed",
    "el disfraz": "disguise",
    disfrazarse: "to disguise oneself. to dress up",
    enmascarado: "masked",
    "llevar m\u00e1scaras": "to wear masks",
    destacar: "to stand out",
    "la tauromaquia": "bullfighting",
    "el toreo": "art of bullfighting",
    "la plaza de toros": "bullring",
    "la fiesta taurina": "bullfighting festival",
    "el matador": "bullfighter (who kills the bull)",
    "el torero": "bullfighter",
    "el traje de luces": "bullfighter's costume",
    "la lidia": "bullfight",
    lidiar: "to fight",
    "la novillada": "bullfighting with young bulls",
    "el encierro": "running of the bulls",
    "la gente acostumbra a comer en las terrazas":
      "people are accustomed to eating on terraces",
    "el pincho": "tapa (on bread)",
    "salir de tapeo": "to go out to eat tapas",
    "salir a picar algo": "to go out to have a bite",
    tapear: "to eat tapas",
    "hacer la sobremesa": "to have an after-meal conversation",
    "el mercadillo": "street market",
    "la vida nocturna": "night life",
    "domir / echar la siesta": "to have a siesta",
    "los horarios de las comidas tard\u00edos": "late eating hours",
    "la costumbre de saludar a la gente con dos besos":
      "custom of greeting people by kissing both cheeks"
  },
  //5.2 La Gastronomía
  {
    "la alimentaci\u00f3n": "diet (nutrition)",
    "el cultivo": "crop",
    "la dieta mediterr\u00e1nea": "mediterranean diet",
    "el plato": "dish",
    "el postre": "dessert",
    "la raci\u00f3n": "portion",
    "la receta": "recipe",
    "la reposteria": "confectionary",
    "el alimento": "food product",
    "el caldo": "broth",
    "la cazuela": "casserole",
    "la cocci\u00f3n al horno": "baking",
    "la cocina": "cooking. kitchen. cuisine. cooker",
    "la cocina espa\u00f1ola": "spanish cuisine",
    "el cocinero": "chef",
    "el comedor": "dining room",
    culinario: "culinary 18 gaston\u00f3mico/a",
    hambriento: "hungry",
    "el ingrediente": "ingredient 21 maduro",
    picante: "spicy",
    refrescante: "refreshing",
    rico: "delicious",
    "saber a ajo": "to taste of garlic",
    "el sabor": "flavour",
    "saborear un plato": "to savour a dish",
    "la sal": "salt",
    "la salsa picante": "hot sauce",
    sediento: "thirsty 31 ser cocinero/a experto/a",
    "la calidad": "quality",
    "el clima": "climate",
    "los comistibles": "foodstuffs",
    "la industria alimenticia": "food industry 36 el productor",
    "los productos frescos": "fresh produce 38 la recogida",
    "la recolecci\u00f3n": "harvest (fruit)",
    "el terreno": "land",
    "las tierras de cultivo": "agricultural land",
    "el comensal": "diner",
    "el camarero": "waiter",
    "la hamburgueser\u00eda": "burger bar",
    "el restaurante": "restaurant",
    "el men\u00fa gastron\u00f3mico": "gourmet menu",
    "el men\u00fa tur\u00edstico": "cheap. set menu",
    "el men\u00fa del d\u00eda": "daily special menu",
    "ofrecer un ambiente acogedor": "to offer a friendly atmosphere",
    "el plato combinado": "set main course",
    "se come bien ah\u00ed": "the food's good there",
    "la cafeter\u00eda": "caf\u00e9",
    "el bar de enfrente": "bar over the road",
    "el club nocturno": "night club",
    "la taberna": "bar. tavern",
    "la tasca": "bar",
    "la alimentaci\u00f3n poco saludable": "unhealthy eating",
    "la alimentaci\u00f3n saludable": "healthy eating",
    "la comida basura": "junk food",
    "la comida r\u00e1pida": "fast food",
    "la dieta equilibrada": "balanced diet",
    "la grasa": "fat",
    nutritivo: "nutritious",
    "el r\u00e9gimen": "diet",
    "ser glot\u00f3n": "to be a glutton",
    "ser goloso": "to have a sweet tooth",
    "la carne a la brasa": "grilled meat",
    "la carne de caza": "game meat",
    "la carne de cerdo": "pork",
    "la carne de vaca": "beef",
    "el conejo": "rabbit",
    "el cordero": "lamb",
    "el embutido": "sausage",
    "el filete": "steak",
    "el jam\u00f3n serrano": "spanish cured ham (lit 'ham from the mountains')",
    "la morcilla": "blood sausage. black pudding",
    "el pollo asado": "roasted chicken",
    "la ternera": "veal",
    "los mariscos": "seafood",
    "la almeja": "clam",
    "la anchoa": "anchovy",
    "el at\u00fan": "tuna",
    "el bacalao": "cod",
    "el calamar": "squid",
    "la gamba": "prawn",
    "el mejill\u00f3n": "mussel",
    "la merluza": "hake",
    "el pescado a la plancha": "grilled fish",
    "el pulpo": "octopus",
    "la trucha": "trout",
    "la aceituna": "olive",
    "la almendra": "almond",
    "el albaricoque": "apricot",
    "la avellana": "hazelnut",
    "la cereza": "cherry",
    "la ciruela": "plum",
    "la fresa": "strawberry",
    "el higo": "fig",
    "el lim\u00f3n": "lemon",
    "el melocot\u00f3n": "peach",
    "la uva": "grape",
    "el \u00e1randano": "blueberry",
    "la frambuesa": "raspberry",
    "el ajo": "garlic",
    "la berenjena": "aubergine",
    "la cebolla": "onion",
    "los garbanzos": "chickpeas",
    "las hierbas arom\u00e1ticas": "aromatic herbs",
    "la jud\u00eda": "bean",
    "las legumbres": "pulses",
    "la pimienta": "pepper",
    "el pimiento verde": "green pepper",
    "el pimiento morr\u00f3n": "red pepper",
    "la seta": "mushroom",
    "el champi\u00f1\u00f3n": "button mushroom",
    "las verduras": "vegetables",
    "la zanahoria": "carrot",
    "el arroz": "rice",
    "la empanada": "pasty",
    "la galleta": "biscuit",
    "la mantequilla": "butter",
    "la miel": "honey",
    "la nata": "cream",
    "el pan con ajo": "garlic bread",
    "el pan con tomate": "tomato bread",
    "el pastel de hojaldre": "filo pastry cake",
    "el queso de cabra": "goat's cheese",
    "el queso manchego": "manchego cheese",
    "el queso de oveja": "sheep's cheese",
    "el turr\u00f3n": "nougat",
    "la cerveza": "beer",
    "la denominaci\u00f3n de origen": "certificate of origin (of wine)",
    "la litrona": "one-litre bottle of beer",
    "el refresco": "soft drink",
    "la sidra": "cider",
    "el zumo": "juice",
    "vamos a tomar algo/una copa": "let's have a drink",
    "el vino tinto": "red wine",
    "la juerga": "binge (eating)",
    "la carnicer\u00eda": "butcher's",
    "la confiter\u00eda": "sweet shop",
    "la pasteler\u00eda": "cake shop",
    "la fruter\u00eda": "greengrocer's",
    "el supermercado de barrio": "local supermarket",
    "la tienda de comestibles": "grocer's",
    "la tienda de ultramarinos": "grocer's",
    alimentar: "to feed",
    "dar de comer": "to give food",
    asar: "to roast",
    calentar: "to heat up",
    cocer: "to cook",
    "los calamares a la romana": "squid in batter",
    "el cochinillo asado": "roast suckling pig",
    "el cocido madrile\u00f1o": "madrid stew",
    "la crema catalana": "creme brulee",
    "la fabada asturiana": "bean and pork stew (from asturias)",
    "las gambas al ajillo": "prawns with garlic",
    "el gazpacho andaluz": "andalusian cold tomato soup",
    "el pulpo a la gallega": "galician style octopus",
    "la tortilla espa\u00f1ola": "spanish omelette"
  },
  //5.3 Las Lenguas
  {
    bilingüe: "bilingual",
    "el dialecto": "dialect",
    "la lengua": "language (tongue)",
    "el idioma": "language",
    "el habla": "speech",
    "el hablante": "speaker",
    "el int\u00e9rprete": "interpreter",
    "la lengua cooficial": "co-official language",
    "la lengua minoritaria": "minority language",
    "el significado": "meaning",
    "la traducci\u00f3n": "translation",
    "el uso": "usage",
    "el lenguaje": "language (capacity to express oneself in language)",
    "el abecedario": "alphabet",
    callar: "to be quiet",
    hablador: "talkative",
    "el ling\u00fcista": "linguist",
    "la ling\u00fc\u00edstica": "linguistics",
    "la caracter\u00edstica ling\u00fcistica": "linguistic characteristic",
    coloquial: "colloquial (familiar)",
    "el argot": "slang",
    "derivado de": "derived from",
    "la desaparici\u00f3n de las lenguas": "the disappearance of languages",
    "un idioma en peligro de extinci\u00f3n":
      "a language in danger of extinction",
    "la diversidad ling\u00fc\u00edstica": "linguistic diversity",
    "en el \u00e1mbito ling\u00fc\u00edstico":
      "in the field/domain of language",
    "un entorno hispanohablante": "a spanish-speaking environment",
    "el habla local": "local speech",
    "la lengua escrita": "written language",
    "la lengua extranjera": "foreign language",
    "la lengua franca": "lingua franca",
    "la lengua hablada": "spoken language",
    "la lengua materna": "mother tongue",
    "la lengua procedente/que deriva del lat\u00edn":
      "language derived from latin",
    "la letra": "letter",
    "el monoling\u00fcismo": "monolingualism",
    "el origen del espa\u00f1ol se remonta a la \u00e9poca romana":
      "the origin of spanish goes back to roman times",
    "el patrimonio ling\u00fc\u00edstica": "linguistic heritage",
    "el pluriling\u00fcismo enriquece culturalmente":
      "multilingualism is culturally enriching",
    "la real academia espa\u00f1ola": "royal spanish academy",
    "el refr\u00e1n": "proverb",
    "el sentido": "sense",
    "sentirse orgulloso de su idioma significar":
      "to feel proud of one's language to mean",
    "la divulgaci\u00f3n": "dissemination",
    "el espa\u00f1ol es la cuarta lengua m\u00e1s hablada del mundo":
      "spanish is the fourth-most spoken language in the world",
    "la difusi\u00f3n de la lengua espa\u00f1ola":
      "spread of the spanish language",
    difundir: "to disseminate",
    "los medios de comunicaci\u00f3n": "media",
    "la transmisi\u00f3n oral": "spoken transmission",
    "una lengua de comunicaci\u00f3n internacional":
      "a language of international communication",
    "el uso del castellano a trav\u00e9s de la red":
      "use of spanish on the internet",
    "el veh\u00edculo de comunicaci\u00f3n": "vehicle of communication",
    "el aprendizaje y el uso de un idioma": "learning and using language",
    "aprender una lengua": "to learn a language",
    "el aprendizaje ling\u00fc\u00edstico": "language learning",
    "practicar una lengua": "to practise a language",
    "dominar una lengua": "to master a language",
    "el biling\u00fcismo": "bilingualism",
    "la charla": "talk",
    charlar: "to talk",
    chatear: "to chat",
    "la comunicaci\u00f3n": "communication",
    "la destreza ling\u00fc\u00edstica": "linguistic skill",
    "expresarse en un idioma": "to express oneself in a language",
    interpretar: "to interpret",
    "la interpretaci\u00f3n": "interpretation",
    "la pronunciaci\u00f3n": "pronunciation",
    "los sonidos de una lengua": "sounds of a language",
    "sustituir una palabra por otra": "to replace one word with another",
    traducir: "to translate",
    "el traductor": "translator",
    "tratar de usted": "to address formally",
    tutear: "to address informally",
    "el castellano": "castilian",
    "el gallego": "galician",
    "el euskera": "basque",
    "el castellanohablante": "spanish speaker",
    "el catalanohablante": "catalan-speaker",
    "el gallegohablante": "galician-speaker",
    "el vascohablante": "basque speaker",
    "el castellano se transmite de generaci\u00f3n en generaci\u00f3n":
      "spanish is passed on from one generation to the next",
    "hablar castellano como primer idioma":
      "to speak spanish as one's language",
    "el canal de televisi\u00f3n catalana": "catalan TV channel",
    "la emisora de radio en gallego": "galician radio station",
    "la lengua mayoritaria": "majority language",
    "la zona monoling\u00fce": "monolingual area",
    "el g\u00e9nero": "gender",
    "la oraci\u00f3n": "sentence",
    "la frase": "phrase",
    "el p\u00e1rrafo": "paragraph",
    "el seseo": "pronunciation of c and z as s",
    "el tilde": "written accent",
    "la voz": "voice/word"
  }
];

export default DATA;
